title = "TOML Example"

[owner]
name = "Tom Preston-Werner"

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers-alpha]
ip = "10.0.0.1"
role = "frontend"

[servers-beta]
ip = "10.0.0.2"
role = "backend"

